# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SWAT2' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!

  # Pods for SWAT2
  pod 'Firebase/Core'
  pod 'Firebase/Database'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'ReactNativeSearchBar', :path => '../node_modules/react-native-search-bar'

end

